version: '3'
services:
  node-app:
    build: .
    # ports:
    #   - '3000:4000'
    environment:
      - PORT=4000
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pjuancruz
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    ports:
      - '3000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo-db:
