version: '3'
services:
  node-app:
    build: .
    ports:
      - '3000:4000'
    environment:
      - PORT=4000

  mongo:
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pjuancruz
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: